name: Prototype Contribution Survey Form
description: A survey to asses contribution by individuals to the autonomous organisation or SecretDecks directly
title: "<year(number)>-<month(number)>-<your-name>-SecretDecks-ContributionSurvey"
labels: [Contribution Survey]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this Contribution Survey.
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: dropdown
  id: contributer
  attributes:
    label: Contributer
    multiple: false
    options:
    - Dan
    - Tyler
    - Heather
    - Stephen
- type: input
  id: terms
  attributes:
    label: General Information
    description: This provides an overall summary or context of a member, when they became involved and how many days they have worked. This could be supplemented with a contribution vote by peers to capture the more intangible contribution a member has made.
    options:
    - label:  Date joined ACO - [Day/Month/Year]
      required: true
    - label: Days / Hours worked overall - [00 Days/Hours]
      required: true
    - label: Cost of contribution (from member perspective) - [$ 0]
      required: true
      
- type: dropdown
  id: vote
  attributes:
    label: Contribution vote
    description: Please select colleagues to confirm your contribution
    required: true
    multiple: true
    options:
    - DanM3rcurius
    - Tyler
    - Heather
    - Stephen
    - Tamagit
      
- type: checkboxes
  id: Development
  attributes:
    label: Development
    description:  Each work area will be divided into appropriate categories (e.g. Code, UX etc.) and be accompanied with an "Outputs" section where members can record what they have produced, built, documented etc.
    options:
    - label: Code
      required: false
    - label: UX
      required: false
    - label: Test
      required: false
    - label: Support
      required: false
- type: textarea
  id: zzzz
  attributes:
    label: Outputs 
    placeholder: What has been produced, built, documented etc.
    render : text
 
