
name: Auction Current Bid 
on: push
jobs:
  Auction:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current bid
        id: var
        run: |
         ./github/workflows/1stAuctionRun.sh
      -  name: "Create issue for Bid"
         uses: dacbd/create-issue-action@v1
         with:
          token: ${{ github.token }}
          title: _${{ steps.var.outputs }} ADA is the current bid
          body: 
      -  run: |
           echo ${{ steps.var.outputs }}

    
          
 
          
    
    
        
 

