
name: Auction Current Bid 
on: push
jobs:
  Auction:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: save current bid
        id: var
        run: |
          curl -H "project_id:  ${{ secrets.BLACKFROST }}" \
          "https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1v8avhxf9rsue8ghqxwkg6kscfxxeu97xs7sq3u4hzyccn5c7tnnnu" | jq '.amount[0].quantity'
      -  name: "Create issue for Bid"
         uses: dacbd/create-issue-action@v1
         with:
          token: ${{ github.token }}
          title: _${{ steps.var.outputs.response }} ADA is the current bid
          body: ${{ fromJson(steps.var.outputs.response).amount[0].quantity }} ADA is the current bid
     

    
          
 
          
    
    
        
 

