on: push
jobs:
  deployment:
     runs-on: ubuntu-latest
     steps:
     - name: Request
       id: Bid
       uses: fjogeleit/http-request-action@v1
       with:
         url: 'https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr1v8avhxf9rsue8ghqxwkg6kscfxxeu97xs7sq3u4hzyccn5c7tnnnu'
         method: 'GET'
         contentType: "application/json"
         customHeaders: '{"project_id": "${{secrets.BLACKFROST}}"}'
     -  name: "Create issue for Bid"
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ github.token }}
          title: ${{ fromJson(steps.Bid.outputs.response).amount[0].quantity|=tonumber / 1000000 }} ADA is the current bid
     -  run: |
         echo ${{ steps.Bid.outputs.response }}
         echo ${{ fromJson(steps.Bid.outputs.response).amount[0].quantity }} 
     - name: Adding Markdown
       run: echo ${{ fromJson(steps.Bid.outputs.response).amount[0].quantity }} >> $GITHUB_STEP_SUMMARY
        
      
